import json
import csv
import os
import numpy as np
from datetime import datetime
from pathlib import Path

# Try to import sentence-transformers, install if needed
try:
    from sentence_transformers import SentenceTransformer
except ImportError:
    print("Installation de sentence-transformers...")
    import subprocess
    subprocess.check_call(["pip", "install", "sentence-transformers"])
    from sentence_transformers import SentenceTransformer

def load_data_from_json(filepath):
    """Load data from JSON file"""
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def _check_model_cached(model_name):
    """Check if a HuggingFace model is already in the local cache."""
    cache_dir = Path(os.environ.get("HF_HOME", Path.home() / ".cache" / "huggingface")) / "hub"
    # HF stores models as models--org--name
    model_dir_name = f"models--{model_name.replace('/', '--')}"
    return (cache_dir / model_dir_name).exists()

def _load_model(model_name):
    """Load model, using offline mode if cached (avoids SSL issues on corporate networks)."""
    if _check_model_cached(f"sentence-transformers/{model_name}"):
        os.environ["HF_HUB_OFFLINE"] = "1"
        os.environ["TRANSFORMERS_OFFLINE"] = "1"
        print("  -> Modele trouve en cache local, chargement offline...")
    return SentenceTransformer(model_name)

def create_embeddings(data_list, model_name="all-MiniLM-L6-v2"):
    """
    Create embeddings for enterprise data
    all-MiniLM-L6-v2 is fast and small (perfect for POC)
    """
    print(f"Chargement du modèle d'embedding: {model_name}...")
    model = _load_model(model_name)
    
    embeddings_data = []
    
    for idx, company in enumerate(data_list):
        print(f"Embedding {idx + 1}/{len(data_list)}: {company['name']}")
        
        # Combine relevant fields for embedding
        text_to_embed = f"{company['name']} {company['secteur']} {company['forme_juridique']} SIREN: {company['siren']}"
        
        # Generate embedding (384-dimensional vector for this model)
        embedding = model.encode(text_to_embed, convert_to_numpy=True)
        
        # Store original data + embedding
        company_with_embedding = {
            **company,
            "embedding": embedding.tolist(),  # Convert to list for JSON serialization
            "embedding_model": model_name,
            "embedding_dimension": len(embedding),
            "embedding_timestamp": datetime.now().isoformat()
        }
        
        embeddings_data.append(company_with_embedding)
    
    return embeddings_data, model

def save_embeddings(embeddings_data, output_filename):
    """Save embeddings to JSON file"""
    with open(output_filename, 'w', encoding='utf-8') as f:
        json.dump(embeddings_data, f, indent=2, ensure_ascii=False)
    print(f"Embeddings sauvegardés dans {output_filename}")

def save_embeddings_csv(embeddings_data, output_filename):
    """Save embeddings to CSV (with embedding as concatenated string)"""
    if not embeddings_data:
        return
    
    # Prepare data for CSV
    csv_data = []
    for item in embeddings_data:
        embedding_str = ",".join(str(x) for x in item['embedding'][:10])  # First 10 dims as preview
        csv_data.append({
            "name": item['name'],
            "siren": item['siren'],
            "siret": item['siret'],
            "secteur": item['secteur'],
            "embedding_preview": embedding_str + "...",
            "embedding_dimension": item['embedding_dimension'],
            "embedding_model": item['embedding_model']
        })
    
    with open(output_filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=csv_data[0].keys())
        writer.writeheader()
        writer.writerows(csv_data)
    
    print(f"Aperçu des embeddings sauvegardé dans {output_filename}")

def display_embedding_stats(embeddings_data):
    """Display statistics about embeddings"""
    print("\nStatistiques des embeddings:")
    print(f"  • Nombre d'entreprises: {len(embeddings_data)}")
    print(f"  • Dimension des vecteurs: {embeddings_data[0]['embedding_dimension']}")
    print(f"  • Modèle utilisé: {embeddings_data[0]['embedding_model']}")
    print(f"\n  Exemple d'embedding pour {embeddings_data[0]['name']}:")
    print(f"    Premières 10 dimensions: {embeddings_data[0]['embedding'][:10]}")

if __name__ == "__main__":
    print("Étape 2 - Embedding des données...\n")
    
    # Find the latest JSON file generated by fetch_api_data.py
    json_files = list(Path(".").glob("entreprises_data_*.json"))
    if not json_files:
        print("Aucun fichier entreprises_data_*.json trouvé!")
        print("Exécute d'abord fetch_api_data.py")
        exit(1)
    
    latest_json = max(json_files, key=lambda p: p.stat().st_mtime)
    print(f"Lecture données depuis: {latest_json}\n")
    
    # Load data
    data = load_data_from_json(latest_json)
    
    # Create embeddings
    embeddings_data, model = create_embeddings(data)
    
    # Save results
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # JSON with full embeddings
    json_output = f"entreprises_embeddings_{timestamp}.json"
    save_embeddings(embeddings_data, json_output)
    
    # CSV with embedding preview
    csv_output = f"entreprises_embeddings_{timestamp}.csv"
    save_embeddings_csv(embeddings_data, csv_output)
    
    # Display stats
    display_embedding_stats(embeddings_data)
    
    print("\nÉtape 2 - Terminée!")
    print("Les embeddings sont prêts pour l'étape 3 (Stockage dans Snowflake)")
